class Error(Exception):
    pass


class CustomError(Error):
    pass
